### ISSUE TITLE
Stuck on go-jmespath

### ISSUE THREAD

**Issue by jimitheat** [algorand/sandbox#105]
It's trying to download go-jmespath v.0.0.3 and it gets stuck there when it's trying to docker compose in gitbash. 

Then the whole process fails. 

Can you see if there's meant to be that version?

It's attempting to visit the following repository and it gets stuck there --> going to it, that site fails. 
https://github.com/jmespath/go-jmespath%20v0.3.0

----------
github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af h1:pmfjZENx5imkbgOkpRUYLnmbU7UEFbjtDA2hxJ1ichM=
github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af/go.mod h1:Nht3zPeWKUH0NzdCt2Blrr5ys8VGpn0CEB0cQHVjt7k=

**Comment by fabrice102** [comment]
Can you access https://github.com/jmespath/go-jmespath from your machine?
Are you behind a VPN/proxy that strongly limits some access?
How fast is your Internet connection?

Can you provide all the versions of sandbox (`git rev-parse HEAD`), Docker, OS, git-bash?
Are you on the latest versions for all?

What error do you see in `sandbox.log` when it fails?

**Comment by winder** [comment]
No update. Please reopen if this is still an issue.
