### ISSUE TITLE
'docker-compose' replaced by 'docker compose'

### ISSUE THREAD

**Issue by EmanueleOversonic** [algorand/sandbox#114]
### Subject of the issue

'docker-compose' command has been replaced by 'docker compose' in Docker Compose v2 causing sandbox bug

### Your environment

* Software version: sandbox commit 5064377
* Operating System: Ubuntu 20.04

### Steps to reproduce

1. Install docker as specified at https://docs.docker.com/engine/install/ubuntu/
2. git clone https://github.com/algorand/sandbox.git
3. cd sandbox
4. ./sandbox up

### Expected behaviour

Sandbox run with the default configuration

### Actual behaviour

An error is thrown: `Error: docker-compose is not installed.`

**Comment by abzerdnerd** [comment]
I'm not sure if I should be putting this here or elsewhere but after having this exact problem and doing some searching I found: 
https://www.codegrepper.com/code-examples/python/command+%27docker-compose%27+not+found%2C+but+can+be+installed+with%3A 

Where I found the solution for my problem as:
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
