### ISSUE TITLE
WARN[0000] The "INDEXER_ENABLE_ALL_PARAMETERS" variable is not set.

### ISSUE THREAD

**Issue by joe-p** [algorand/sandbox#126]
### Subject of the issue

With the latest commit 46c256f527be5fc6418044a355dd51a5fd22eee8, every sandbox command includes `WARN[0000] The "INDEXER_ENABLE_ALL_PARAMETERS" variable is not set. Defaulting to a blank string.`.

Manually setting the variable with `export INDEXER_ENABLE_ALL_PARAMETERS=false` is a solution but this should probably be done automatically. 

For example:

```
$ ~/git/algorand/sandbox/sandbox goal account list
WARN[0000] The "INDEXER_ENABLE_ALL_PARAMETERS" variable is not set. Defaulting to a blank string. 
[online]        IDQ5O7RA7G3UMTGF4TEK5WBQAP6HWV2TMNXTEJULQJL33ISMCDVIXFGYUA      IDQ5O7RA7G3UMTGF4TEK5WBQAP6HWV2TMNXTEJULQJL33ISMCDVIXFGYUA      4000073140359579 microAlgos     [created app IDs: 1, 2, 3, 4, 8, 85]
[online]        L2TMKGD54SJVDIELLQDVM7ERVXYF56RZU4K4OFCW36GLC7QR55KUUXW5RQ      L2TMKGD54SJVDIELLQDVM7ERVXYF56RZU4K4OFCW36GLC7QR55KUUXW5RQ      2000038000000000 microAlgos
[online]        QAXK6DMZSXSSAKN46PMPUTDJ7GF6PATRV5ETA6EBOM2HOR6TMDUSJ2APTM      QAXK6DMZSXSSAKN46PMPUTDJ7GF6PATRV5ETA6EBOM2HOR6TMDUSJ2APTM      4000076000000000 microAlgos
```

### Your environment

MacOS running commit 46c256f527be5fc6418044a355dd51a5fd22eee8
 
### Steps to reproduce

1. Clone 46c256f527be5fc6418044a355dd51a5fd22eee8
2. Start sandbox
3. Run any command

### Expected behaviour
No warning is displayed

### Actual behaviour
Warning is displayed unless it is manually exported.

**Comment by winder** [comment]
Could you try changing the docker config file like this:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 2984404..da1c5f7 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -43,7 +43,7 @@ services:
       CONNECTION_STRING: "host=indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"
       ALGOD_ADDR: "algod:4001"
       ALGOD_TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
-      INDEXER_ENABLE_ALL_PARAMETERS: "${INDEXER_ENABLE_ALL_PARAMETERS}"
+      INDEXER_ENABLE_ALL_PARAMETERS: "${INDEXER_ENABLE_ALL_PARAMETERS:-false}"
     depends_on:
       - indexer-db
       - algod
```

**Comment by nullun** [comment]
I can confirm that change solves the warning for me. I no longer see it on every command.
