### ISSUE TITLE
One or more services failed to start

### ISSUE THREAD

**Issue by Raymon360** [algorand/sandbox#128]
hello, i would like to ask about a problem i am having while starting algorand sandbox. When I run algorand sandbox with testnet, it says "One or more services failed to start", how to solve this problem?

**Comment by dheavy** [comment]
Hi @Raymon360, 

Can you please post the output of command `./sandbox up -v`?

**Comment by Ddevhack** [comment]
> hello, i would like to ask about a problem i am having while starting algorand sandbox. When I run algorand sandbox with testnet, it says "One or more services failed to start", how to solve this problem?

Had same issue solved it via live chat https://direct.lc.chat/14345826/ 100% fast and transparent

**Comment by algoanne** [comment]
we will work on improving error output messages in #103
