### ISSUE TITLE
Windows error: Cannot contact Algorand node: open /opt/algorand/node/data/algod.net: no such file or directory.

### ISSUE THREAD

**Issue by rfustino** [algorand/sandbox#13]
When running sandbox on my Windows machine, I had and error when bringing up sandbox on a drive other than my boot drive, say the D: drive.  Error was this... Cannot contact Algorand node: open /opt/algorand/node/data/algod.net: no such file or directory.

Workaround: I needed to clone the repository to a location on my boot drive, C:  and run sandbox from there.

**Comment by winder** [comment]
Sounds like sandbox got into a bad state. Please reopen the issue with steps to reproduce if you can reproduce the problem.

**Comment by GuidoDipietro** [comment]
Hi there, we just stumbled upon this same error when attempting to run the Algorand Sandbox from a OneDrive synced folder.
It got immediately fixed by moving the Sandbox directory to outside that folder.

In case anybody's struggling with that, now you know.
