### ISSUE TITLE
Seed missing from /v2/blocks/ in dev mode

### ISSUE THREAD

**Issue by jzjones** [algorand/sandbox#137]
### Subject of the issue

Seed is missing from JSON response when in dev mode

### Your environment

I'm on latest sandbox master, running Ubuntu

### Steps to reproduce

```
ben@Algo-Guidarelli:~$ curl -s localhost:4001/v2/blocks/10 -H "X-Algo-API-Token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" | jq '.block | keys'
[
  "fees",
  "frac",
  "gen",
  "gh",
  "prev",
  "proto",
  "rate",
  "rnd",
  "rwcalr",
  "rwd",
  "spt",
  "tc",
  "ts",
  "txn",
  "txn256",
  "txns"
]
ben@Algo-Guidarelli:~$ curl -s 'https://node.algoexplorerapi.io/v2/blocks/22747265' | jq '.block | keys'
[
  "earn",
  "fees",
  "frac",
  "gen",
  "gh",
  "prev",
  "proto",
  "rnd",
  "rwcalr",
  "rwd",
  "seed",
  "tc",
  "ts",
  "txn",
  "txns"
]
```

### Expected behaviour

Seed is populated

### Actual behaviour

Seed is not populated

**Comment by winder** [comment]
Thanks for the report, we've moved the request to go-algorand where this would be fixed: [go-algorand#4423](https://github.com/algorand/go-algorand/issues/4423)
