### ISSUE TITLE
Transactions rejected with http: Request  body too large

### ISSUE THREAD

**Issue by hernandp** [algorand/sandbox#144]
### Subject of the issue

After running several transactions, sandbox may stop processing TXs returning the following error to the client:

```

    Network request error. Received status 400: http: request body too large Error Extra Info: http: request body too large

      at Request.callback (../../node_modules/superagent/src/node/index.js:879:15)
      at fn (../../node_modules/superagent/src/node/index.js:1130:18)
      at IncomingMessage.<anonymous> (../../node_modules/superagent/src/node/parsers/image.js:8:5)
```

### Your environment

Windows Subsystem for Linux (WSL)  v2
```
Linux LAPTOP-QJTRSF6V 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Windows 10, 21H2, Build 19044.1889

Sandbox  commit 453fcd48446dd13197689297280d38b32c1369db

### Steps to reproduce

1. Run several TXs in a row, probably you need to run up > 200s of them
2. Sandbox will eventually reject TXs with reported error

### Expected behaviour

Process all transactions as it should.

### Actual behaviour

Transactions rejected.

**Comment by barnjamin** [comment]
I think this might be related to dryrun more than sandbox, if you're using the same account for creating a ton of apps/assets the payload generated from a call to `createDryrun`  will include _all_ of them. 

A sandbox reset will "fix" it by removing all the extra state but its not ideal. 

There is some work being done to improve dryrun and add a simulate endpoint so you wouldn't need to pass the state for the accounts you're interested in, it'd just be referenced from the ledger directly.

**Comment by hernandp** [comment]
@barnjamin   Thanks, we trigger a lot of dryruns so this is highly probable. Thanks.

**Comment by winder** [comment]
If this is still an issue, please open a bug report on the go-algorand repo.
