### ISSUE TITLE
Add compiler feature from Pyteal to Teal to sandbox

### ISSUE THREAD

**Issue by ernestosperanza** [algorand/sandbox#146]
## Problem

Improve the development experience

## Solution

Add a compile feature from Pyteal to teal.
Compile the Pyteal contracts with one command, like Pyteal:compile

## Urgency

No rush

**Comment by ernestosperanza** [comment]
I can work on this issue if it is required. I have a custom-made system and we cloud implemented in the sandbox, let me know.

**Comment by winder** [comment]
Could you describe your system? I'm not sure what it would mean for Sandbox to have PyTeal support. I could imagine the other way around, where something like PyTest was integrated with sandbox and PyTeal could use it for tests.

**Comment by ernestosperanza** [comment]
Yeah, I guess that is possible, I don't know the scope of the sandbox per se.
I am thinking in a tooling like truffle and Gnache in solidity.
Fell free to close it, If this not apply to sandbox.
