### ISSUE TITLE
./sandbox enter algod

### ISSUE THREAD

**Issue by lanaradmilovic** [algorand/sandbox#177]
![slika](https://user-images.githubusercontent.com/115712547/229302178-1f2f57fd-265d-4462-9fa9-974b5f5b021d.PNG)
Does anyone know why it is not enterning algod?

**Comment by barnjamin** [comment]
is it running? (better go catch it!)

but actually make sure its running with `./sandbox test` 

And also make sure docker desktop is running

**Comment by bbroder-algo** [comment]
we need sandbox doctor

**Comment by lanaradmilovic** [comment]
![slika 1](https://user-images.githubusercontent.com/115712547/229369325-010ca3c1-3259-42e5-9724-ab5ffa0b2146.PNG)
![slika 2](https://user-images.githubusercontent.com/115712547/229369328-b657faee-cd65-4d4f-9f65-6893a47598ff.PNG)

**Comment by algoanne** [comment]
hi @lanaradmilovic, if this is still an issue, can you give us a little more information on your environment and what you did up to this point? 

By the way, you will generally find faster responses to troubleshooting questions on our Discord!
