### ISSUE TITLE
Indexer doesn't update transactions

### ISSUE THREAD

**Issue by hugoburguete** [algorand/sandbox#26]
I've been experimenting this tool but I can't seem to figure out why my indexer doesn't get updated. 

In the below screenshot, I've queried the indexer before and after doing a transaction but the round doesn't seem to update nor do any of my transactions show up:
![image](https://user-images.githubusercontent.com/17925235/108113493-82154b80-708f-11eb-8de6-834081cd4d53.png)

Am I missing something? I've tried removing the containers, removing the docker images and readding them but the issue seems to persist. Can't see anything obvious in the sandbox.log file either.

**Comment by hugoburguete** [comment]
Also noticed there's a `./sandbox clean` command but the transactions are still not showing up :/

**Comment by winder** [comment]
@hugoburguete you aren't missing anything, there is a new protocol version on algod and indexer hasn't been updated yet.

**Comment by hugoburguete** [comment]
@winder Great, thanks for the tip, wasn't aware that nightly was using a development branch. 

I will leave this issue open in case you someone wants to use it as a reminder to use the release config by default but feel free to close it if it's not necessary 👍

**Comment by winder** [comment]
@hugoburguete thanks for the bug report. The development branches will be compatible shortly, and if you get the latest sandbox script, it's now configured to use the release branches by default.
