### ISSUE TITLE
Lock version of stable/nightly to git commits

### ISSUE THREAD

**Issue by chicopaec** [algorand/sandbox#37]
From Discord:

![image](https://user-images.githubusercontent.com/80551253/112363194-83ace180-8cd5-11eb-855f-0380291df572.png)

It seems that sandbox currently downloads the latest version available for stable/nightly rather than manually upgraded via SCM so each algod/indexer version is guaranteed a separate git commit.

This makes the stability of the sandbox worse than it has to be, as new versions of the algod/indexer can be pushed and break the sandbox unless you upgrade the sandbox at the same time.

Instead I propose we hardcode the current version to be downloaded of algod/indexer so developers using the sandbox can always be sure that the sandbox works for day-to-day work without interruptions. Then when developers using the sandbox is ready to upgrade, they can pull down the latest git commits and therefore get the latest stable/nightly versions instead.

**Comment by winder** [comment]
Thanks for the suggestion.

Currently algod is installed from pre-built artifacts in the same manner an end user would install them.

Unfortunately we don't have a good way to programatically fetch the latest indexer releases at the moment so it gets rebuilt each time.
