### ISSUE TITLE
Update algod / indexer during "up"

### ISSUE THREAD

**Issue by winder** [algorand/sandbox#41]
There are some cases where it might be useful to update an existing sandbox deployment to generally speed it up (and make it easier to update).

1. If a set of accounts have been created, on the latest "nightly" release, it might be nice to update to the next nightly version each day.
2. If a branch is being used it would be very convenient to allow an incremental build as new sources are pushed instead of requiring a full rebuild.
3. If a mainnet sandbox is all caught up, it would be nice to swap in the new "stable" binaries instead of running catchup again.

This would require changing the Indexer + Algod scripts / Dockerfile's:

Algod
- if a release channel was used, run `update.sh`
- if a branch was used, run `git pull && make install`

Indexer
- Run `git pull && make install`

## Urgency
Not a high priority, but would definitely be a time saver and would allow you to be more flexible with updating on the fly (without wasting a ton of time re deploying)

**Comment by ryanRfox** [comment]
I like this feature request as a time saver. I also agree it is not a huge priority as `sandbox` users may perform these tasks manually as a workaround.

**Comment by michielmulders** [comment]
**If you want to solve this issue, take a look at our bounty program that rewards improvements to the [Algorand Sandbox](https://gitcoin.co/issue/algorandfoundation/grow-algorand/30/100025839).**

**Comment by overhead525** [comment]
@winder Can you take a look at the above issue I mentioned to see if my solution is what you were looking for?
