### ISSUE TITLE
Quicknet

### ISSUE THREAD

**Issue by plasmatech8** [algorand/sandbox#73]
## Problem

Developers might want to test transactions faster, or test a full deployment, or run unit tests without having to wait for minutes for multiple transactions to finish.

## Solution

A network that processes transactions almost immediately.

## Dependencies

?

## Urgency

Low urgency.

**Comment by barnjamin** [comment]
https://github.com/algorand/sandbox#private-network see the `dev` mode

**Comment by plasmatech8** [comment]
@barnjamin Oh thanks. I didn't realize.
