### ISSUE TITLE
Accounts for private network

### ISSUE THREAD

**Issue by ChrisBagge** [algorand/sandbox#74]
Hi,

"By default you will be given access to a private network. This environment is preloaded with a number of accounts ready to use for testing transactions, and includes an Indexer service configured to synchronize against the private network. Because it doesn't require catching up to one of the long running networks it also starts very quickly."

Can you please explain how to get the information for these accounts to use in test transactions?

Thank you,
Chris

**Comment by barnjamin** [comment]
You can see the accounts that were added with something like `./sandbox goal account list`

**Comment by ChrisBagge** [comment]
thank you!
