### ISSUE TITLE
Missing BRANCH or URL environment variable. Skipping install.

### ISSUE THREAD

**Issue by devendr4** [algorand/sandbox#81]
### Subject of the issue

I'm getting this error when trying to run the command `./sandbox up testnet -v` after cloning the repo on EndeavourOS, an Arch Linux based distribution

![image](https://user-images.githubusercontent.com/39252256/140789182-710091a0-b24b-48d1-8072-73bfcfe71ca7.png)

### Steps to reproduce

1. git clone https://github.com/algorand/sandbox.git
2. cd sandbox
3. ./sandbox up testnet -v

**Comment by barnjamin** [comment]
likely related to https://github.com/docker/compose/issues/8882

**Comment by devendr4** [comment]
yes that was it @barnjamin, I had to downgrade docker-compose to 1.x.x and it worked
