### ISSUE TITLE
docker images in docker hub

### ISSUE THREAD

**Issue by gsmachado** [algorand/sandbox#82]
Hello,

This is rather a question than a bug/feature.

Is this git repo the one that is used to build all images in https://hub.docker.com/u/algorand?

Could you please better specify how the docker hub images are built? (i.e., which git repo contains the Dockerfile etc)

**Comment by gsmachado** [comment]
@ryanRfox do you have a clue? or maybe know someone that could answer me that? 😄

**Comment by winder** [comment]
It is not, the docker images here are their own thing

**Comment by robdmoore** [comment]
+1 for getting official sandbox images pushed to docker hub. If I want to run sandbox on my CI/CD pipeline then I need to wait for ages for it to build the sandbox and if the current code in main branch is busted then it fails (which happened when I ran it today).

If there are official images then we can pull the latest stable one and it will run really quickly and reliably.

**Comment by robdmoore** [comment]
Related: https://github.com/algorand/sandbox/issues/100

**Comment by robdmoore** [comment]
FYI my team has open sourced some code that we use to create performant dev sandbox environments via docker-compose and some images we publish to DockerHub: https://github.com/MakerXStudio/algorand-sandbox-dev#algorand-sandbox-dev.

**Comment by algoanne** [comment]
Closing this issue since it's not really an issue and the questions have been answered.
