### ISSUE TITLE
Installation crashes

### ISSUE THREAD

**Issue by jordan-public** [algorand/sandbox#85]
### Subject of the issue

Trying to install sandbox on Ubuntu 20.04 but it crashes upon startup.

### Steps to reproduce

1.uname -a
Linux MBP 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
2. mkdir algorand
3. cd algorand
4. git clone https://github.com/algorand/sandbox.git
5. ./sandbox up dev -v
libtool is required, but wasn't found on this system
make: *** [Makefile:133: crypto/libs/linux/amd64/lib/libsodium.a] Error 1
ERROR: Service 'algod' failed to build: The command '/bin/sh -c /tmp/images/algod/install.sh     -d "${BIN_DIR}"     -c "${CHANNEL}"     -u "${URL}"     -b "${BRANCH}"     -s "${SHA}"' returned a non-zero code: 2

But libtool is is installed!

### Expected behaviour

it should run without crashing:
./sandbox up dev -v

### Actual behaviour
See 5. above - it crashes

**Comment by barnjamin** [comment]
Hi Jordan, Thanks for reporting.

I just filed a PR to add libtool back to the install script, its linked above. 

If you want to test you can temporarily set your config.dev file to have the following parameters
```
export ALGOD_URL="https://github.com/barnjamin/go-algorand"
export ALGOD_BRANCH="sb-dep-fix"
```

**Comment by jordan-public** [comment]
Thank you Ben for your fast response.

Jordan

**Comment by algoanne** [comment]
sorry for the lingering ticket - we don't believe this is an issue anymore, but let us know if it is.

**Comment by michaelgetachew-abebe** [comment]
I am getting this error repeatedly does the fix above solves it?
