### ISSUE TITLE
Algod doesn't start on hotspot wifi

### ISSUE THREAD

**Issue by tallywiesenberg** [algorand/sandbox#95]
### Subject of the issue

If I run `./sandbox up` while using a hotspot for WIFI, I get the following error `service "algod" is not running container #1`, and I am unable to use `sandbox`.

### Your environment
Processor/kernel info:
`Darwin Tallys-MacBook-Air.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64`
MacOS info:
`System Version: macOS 12.0.1 (21A559)`

### Steps to reproduce

1. use personal hotspot for wifi
2. `git clone https://github.com/algorand/sandbox.git`
3.  `cd sandbox`
4.  `./sandbox up`

### Expected behaviour

behavior as described by the readme

### Actual behaviour
`algod" is not running container #1`

**Comment by winder** [comment]
Do other docker containers that depend on a network work in this environment? It sounds like something that could be specific to the way docker and mac configure the network.

**Comment by tallywiesenberg** [comment]
^ Good question! I suspect you're right.
