### ISSUE TITLE
Unexpected behaviour with Docker 4.4.2 on macOS 12.1

### ISSUE THREAD

**Issue by nullun** [algorand/sandbox#98]
### Subject of the issue

When updating docker to version 4.4.2 the sandbox script will error when performing `./sandbox up -v` However it still successfully launches the containers.
After successfully launching the containers, the following error is given before fully completing the output:
```
 ./sandbox up -v

Bringing up existing sandbox: 'c2c'
.clean file NOT FOUND. Sandbox images will NOT be rebuilt.
* docker-compose up -d
[+] Running 3/3
 ⠿ Container algorand-sandbox-algod     Started                                                                                 0.3s
 ⠿ Container algorand-sandbox-postgres  Started                                                                                 0.2s
 ⠿ Container algorand-sandbox-indexer   Started                                                                                 1.0s

#
#... Cut out some prints.
#

Available accounts
~$ ./sandbox goal account list


Example command to send between two accounts:
./sandbox: line 460: ACCOUNTS[1]: unbound variable
```

I also came across this issue when trying to pipe the output of `./sandbox goal account list | awk '{print $3}'` and it will completely ignore the pipe and just output the full account details.

It feels as though the latest Docker version has changed how the output is presented from the container. Piping the data is completely ignored, but if I enter the algod container and run the same command (`goal account list | awk '{print $3}'`) it works fine. So it's the output from docker.

I updated a couple of the `docker-compose exec` calls in the script to use the `-T` flag and things somewhat started working again, but it wasn't a comprehensive solution so I went back to docker version 4.3.1 for the time being.

### Your environment

algod version
12885100837
3.3.133413.dev [feature/contract-to-contract] (commit #83bccc5c)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand

MacBook Pro M1 running macOS Monterey version 12.1

### Steps to reproduce

1. Use Docker version 4.4.2
2. Launch sandbox with `./sandbox up -v`

**Comment by nullun** [comment]
With the help from barnji and MonopolyMan from Discord we were able to pin point this down to docker-compose rather than docker.

I've found that if in the general preferences you uncheck "Use Docker Compose V2", it will continue to work as before on 4.4.2, so that's at least a temporary solution.

**Comment by nullun** [comment]
I just updated to 4.5.0 and it's unfortunately still an issue. But keeping "Use Docker Compose V2" unchecked still works.

**Comment by sheepsushis** [comment]
> I just updated to 4.5.0 and it's unfortunately still an issue. But keeping "Use Docker Compose V2" unchecked still works.

Thank you, it worked perfectly!

**Comment by fabrice102** [comment]
I believe the issue is linked to https://github.com/docker/compose/issues/9104
See also https://stackoverflow.com/questions/71029547/impossible-to-redirect-output-of-docker-compose-v2-on-macos

**Comment by shiqizng** [comment]
Keep "Use Docker Compose V2" unchecked seems to be a temporary solution.
